"""dropped course and stud id columns

Revision ID: 06a9a4c90125
Revises: a7267faa6ce4
Create Date: 2023-09-07 21:00:54.255991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06a9a4c90125'
down_revision: Union[str, None] = 'a7267faa6ce4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_constraint('fk_grades_courses_id_courses', type_='foreignkey')
        batch_op.drop_constraint('fk_grades_students_id_students', type_='foreignkey')
        batch_op.drop_column('courses_id')
        batch_op.drop_column('students_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('students_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('courses_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_grades_students_id_students', 'students', ['students_id'], ['id'])
        batch_op.create_foreign_key('fk_grades_courses_id_courses', 'courses', ['courses_id'], ['id'])

    # ### end Alembic commands ###
