"""added the teacher_course Association table

Revision ID: 2fb2136566ae
Revises: 666e8ac48710
Create Date: 2023-09-05 23:07:43.782822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fb2136566ae'
down_revision: Union[str, None] = '666e8ac48710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_course',
    sa.Column('courses_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['courses_id'], ['courses.id'], name=op.f('fk_teacher_course_courses_id_courses')),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name=op.f('fk_teacher_course_teacher_id_teachers'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_course')
    # ### end Alembic commands ###
