"""added the grade table and set up the relationship between it and student and course

Revision ID: a7267faa6ce4
Revises: f0af0747c1d9
Create Date: 2023-09-07 20:00:33.007837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7267faa6ce4'
down_revision: Union[str, None] = 'f0af0747c1d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('students_id', sa.Integer(), nullable=True),
    sa.Column('courses_id', sa.Integer(), nullable=True),
    sa.Column('mark', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['courses_id'], ['courses.id'], name=op.f('fk_grades_courses_id_courses')),
    sa.ForeignKeyConstraint(['students_id'], ['students.id'], name=op.f('fk_grades_students_id_students')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('student_course')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_course',
    sa.Column('courses_id', sa.INTEGER(), nullable=True),
    sa.Column('students_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['courses_id'], ['courses.id'], name='fk_student_course_courses_id_courses'),
    sa.ForeignKeyConstraint(['students_id'], ['students.id'], name='fk_student_course_students_id_students')
    )
    op.drop_table('grades')
    # ### end Alembic commands ###
