"""dropped the teacher_courses Association table 

Revision ID: f0af0747c1d9
Revises: 2fb2136566ae
Create Date: 2023-09-05 23:14:20.180449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0af0747c1d9'
down_revision: Union[str, None] = '2fb2136566ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_course')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_course',
    sa.Column('courses_id', sa.INTEGER(), nullable=True),
    sa.Column('teacher_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['courses_id'], ['courses.id'], name='fk_teacher_course_courses_id_courses'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name='fk_teacher_course_teacher_id_teachers')
    )
    # ### end Alembic commands ###
